### ISSUE TITLE
merge governance into gaia repo

### ISSUE THREAD

**Issue by hxrts** [cosmos/governance#41]
@uditvira @dcwalk have been working on improving the governance documentation, making sure it's legible and up to date. Among other things, they have made a [vuepress site with all params and their current + historical values](https://hyphacoop.github.io/governance/params-change/param_index.html), queried periodically from RPC endpoints. The previous method of manually updating is time-consuming and error-prone, so this is an incredible resource that should live as close to gaia as possible.

This repo was originally setup to house a collection of process documents originally created by Gavin + various other resources like a list of parameters + Hub proposals. However, it also introduces yet another surface that needs to be considered within any governance workflow + separately maintained.

I propose we merge this repo into gaia to focus our energy on a single source of truth for cosmos hub governance processes and proposals. The pro's are pretty self evident: reduced coordination cost and maintenance burden. I'm particularly excited to have the param index above as part of the primary cosmos hub docs. The main reason against as far as I can tell is new PRs being opened for every new gov proposal, which could interfere with release processes or just generally become an annoyance since PRs are currently opened for every new proposal, whether or not it reaches the deposit threshold. One way we could alleviate this is moving all proposals to the gaia wiki or otherwise separating them from the PR process.

I'd like to solicit some feedback from @ebuchman @okwme and other stakeholders on this proposal and the preferred way to proceed.

**Comment by nylira** [comment]
Plus one from me!

**Comment by dcwalk** [comment]
This is happening! :rocket: 🍩

Potential steps to wrap up merge: 
- [x] 1. PR into Gaia, in progress: https://github.com/cosmos/gaia/pull/995 (and incidentally closes #11)
- [x] 2. Review and transfer of non-stale issues to gaia repo => proposed below: https://github.com/cosmos/governance/issues/41#issuecomment-932404951
- [x] 2b. Transfer PR https://github.com/cosmos/governance/pull/28
- [x] 3. PR readme here with notice to governance of deprecation => #47 
- [ ] 4. Formally archive governance repo (and update repo description?)
- [x] 5. Announce / update in Discord + Forum? => https://forum.cosmos.network/t/about-the-governance-category/1713

**Comment by hxrts** [comment]
Thanks for the update dc!

**Comment by dcwalk** [comment]
#### Issue and PR migration 

Transfer:
- https://github.com/cosmos/governance/pull/28
- https://github.com/cosmos/governance/issues/45
- https://github.com/cosmos/governance/issues/38
- https://github.com/cosmos/governance/issues/34
- https://github.com/cosmos/governance/issues/30
- https://github.com/cosmos/governance/issues/20 => templates there? :heavy_check_mark: 
- https://github.com/cosmos/governance/issues/16 => review and think abt what more do we want now? :heavy_check_mark: 

More investigation:
- ~~https://github.com/cosmos/governance/issues/21~~ => maybe too big? can we say a version is done and refinements elsewhere?
- ~~https://github.com/cosmos/governance/issues/1~~ => leaning toward stale given contemporary discussions 

Will close during this merge:
- https://github.com/cosmos/governance/issues/41
- https://github.com/cosmos/governance/issues/11
- https://github.com/cosmos/governance/issues/2 => ~~I think we can say that this will be handled by new param. and script is in our fork, the new repo. We can plan to refine there!?~~ update: I think we still need to deal with this

**Comment by dcwalk** [comment]
Updated text for forum [governance section description](https://forum.cosmos.network/t/about-the-governance-category/1713): 

> Discussions and proposals for community pool spends, parameter changes, text (signalling), and software upgrades to Cosmos Hub (Gaia).
> 
> Cosmos Hub governance is described in-depth at [hub.cosmos.network](https://hub.cosmos.network/main/governance/). If you would like to make a proposal start by reviewing about the [drafting process and best practices](https://hub.cosmos.network/main/governance/best_practices.html)!

**Comment by dcwalk** [comment]
Okay! All issues transfered to gaia that are current, tagged with `governance` and `docs` as appropriate. So we have a current set of issues here: https://github.com/cosmos/gaia/labels/governance.

**Comment by dcwalk** [comment]
Outstanding: (from comment above)
- 2b. Transfer PR https://github.com/cosmos/governance/pull/28 <-- I don't actually think I can do this as not the submitter, but also I'm not super strong on gh so happy to be corrected
- 4. Formally archive governance repo 
- 5. Announce / update in Discord + Forum

**Comment by hxrts** [comment]
@JoeDirtay what's the status on this PR?

**Comment by JoeDirtay** [comment]
This has already been voted on and approved.  https://www.mintscan.io/cosmos/proposals/48

TBH I haven't looked at this in a while if there are new developments happening.

Thanks :)

**Comment by hxrts** [comment]
merged

**Comment by dcwalk** [comment]
I've mentioned in discord + on the forum (tho I think as a new user/first post I might need a mod approval there)

**Comment by hxrts** [comment]
now live!
